"""Audit every notebook in the corpus for API currency.

A notebook teaches an agent whatever API surface it uses, so a stale
notebook is corpus poison: the index would serve raw-Tapis or old-dapi
idioms as if they were current. This script classifies each notebook
and writes NOTEBOOKS.md, the status table of record.

Classes:
  current-dapi    DSClient with ds.jobs.generate / workflows surface
  old-dapi        earlier dapi surface (auth.init, generate_job_info)
  raw-tapisv3     tapipy driven directly
  local-only      no job submission; post-processing or teaching material

Run: .venv/bin/python scripts/audit_notebooks.py
"""

from pathlib import Path

from designsafe_mcp.audit import classify, code_of

ROOT = Path(__file__).parent.parent
SCAN = [ROOT / "notebooks", ROOT.parent / "dapi" / "examples"]

# UW notebooks we have already modernized into executed dapi examples.
SUPERSEDED = {
    "freeFieldJupyterPM4Sand": "dapi/examples/opensees/pm4sand/DS_PM4Sand_FreeField_Solution.ipynb",
    "OpenSeesMP": "dapi/examples/opensees/OpenSeesMP-dapi.ipynb",
    "GlobalSensitivity": "dapi/examples/quoFEM-sensitivity/quoFEM-sensitivity-dapi.ipynb",
}


def main() -> None:
    rows = []
    for base in SCAN:
        if not base.exists():
            continue
        for p in sorted(base.rglob("*.ipynb")):
            if ".ipynb_checkpoints" in str(p) or "_staged" in str(p):
                continue
            rel = str(p.relative_to(ROOT.parent))
            status = classify(code_of(p))
            superseded = next((v for k, v in SUPERSEDED.items() if k in str(p)), "")
            rows.append((rel, status, superseded))

    lines = [
        "# Notebook corpus status",
        "",
        ("Generated by `scripts/audit_notebooks.py`; regenerate after any "
         "mirror update. A notebook marked anything other than "
         "`current-dapi` or `local-only` teaches a stale API surface and "
         "must not seed a snippet until modernized."),
        "",
        "| notebook | status | superseded by |",
        "|---|---|---|",
    ]
    counts: dict[str, int] = {}
    for rel, status, sup in rows:
        counts[status] = counts.get(status, 0) + 1
        lines.append(f"| {rel} | {status} | {sup} |")
    lines += ["", "Counts: " + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())), ""]
    (ROOT / "NOTEBOOKS.md").write_text("\n".join(lines))
    print(f"{len(rows)} notebooks -> NOTEBOOKS.md")
    for k, v in sorted(counts.items()):
        print(f"  {k:14s} {v}")


if __name__ == "__main__":
    main()
