"""Derive eval cases from the tested notebooks themselves.

Each tested snippet's source notebook opens with a human-written
description of the problem. That prose becomes the eval request and
the snippet's app becomes the expected decision, so the eval corpus
grows automatically with the notebook corpus and never drifts from it.

Run: .venv/bin/python scripts/derive_cases.py
Writes: evals/cases-notebooks.yaml (committed; review the diff).
"""

import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).parent.parent
SNIPPETS = yaml.safe_load((ROOT / "designsafe_mcp" / "snippets.yaml").read_text())


def _intro(nb_path: Path) -> str:
    """First substantive markdown prose in the notebook, cleaned."""
    nb = json.loads(nb_path.read_text(errors="ignore"))
    for cell in nb.get("cells", []):
        if cell.get("cell_type") != "markdown":
            continue
        text = "".join(cell.get("source", []))
        text = re.sub(r"^#.*$", "", text, flags=re.MULTILINE)          # headings
        text = re.sub(r"!\[[^\]]*\]\([^)]*\)", "", text)        # images
        text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)    # links
        text = "\n".join(
            ln for ln in text.splitlines()
            if not re.search(r"University|SimCenter|Group|@", ln))  # bylines
        text = " ".join(text.split())
        if len(text) > 120:
            return text[:600]
    return ""


def main() -> None:
    cases = []
    for s in SNIPPETS["snippets"]:
        rel = Path(s["source"])
        path = (ROOT.parent / rel) if rel.parts[0] in ("dapi", "workflows") else ROOT / rel
        intro = _intro(path)
        if not intro:
            print(f"skip {s['id']}: no usable intro prose")
            continue
        case = {
            "id": f"nb-{s['id']}",
            "request": intro,
            "expect": {"app_id": s["app_id"]},
            "derived_from": s["source"],
        }
        for arg in s.get("extra_app_args", []):
            if arg.get("name") == "Main Program":
                case["expect"]["main_program"] = arg["arg"]
        cases.append(case)

    header = (
        "# GENERATED by scripts/derive_cases.py from the tested snippet\n"
        "# corpus; regenerate after snippets.yaml changes. Requests are\n"
        "# the notebooks' own intro prose, expectations are the snippet\n"
        "# records. Do not hand-edit.\n"
    )
    out = ROOT / "evals" / "cases-notebooks.yaml"
    out.write_text(header + yaml.safe_dump({"cases": cases}, sort_keys=False,
                                           width=76, allow_unicode=True))
    print(f"{len(cases)} cases -> {out}")


if __name__ == "__main__":
    main()
